Release 3.9.0 (2024-06-25)
### Features

* [IsolateBuyerAndSellerCodeExecution] Add wrapper for buyer's reportWin() udf
* [reporting] Enable reportResult execution for topLevelSeller
* Add chaffing feature flags in SFE/BFE.
* add EventMessage to log context
* Add request creation timestamp to ProtectedAuctionInput
* Add request/response to ExecuteInternal on async clients
* Add tee-container-log-redirect option in terraform
* Bash script for ASG and Cloud Map Custom HealthChecks
* Consented request replace enable_adtech_code_logging in Bidding Server
* Create inference model store for model management
* Create logging library for inference consented logs
* Debug Reporting for Bid Currency
* decrease aws/build_and_test duration by ~75%
* Feature Flag for TLS in Service Mesh
* Force the ML model reset with the probability of 0.1%
* Forward per request consented debugging config to roma callback
* Implement AWS Cloud Un-Map
* Implement new SFE <> BFE request format for chaffing
* Implement the probabilistic model reset for PyTorch
* Implement the probabilistic model reset for TensorFlow.
* Load Test Flag for AWS
* Log consented debugging information in inference sidecar
* log EventMessage in servers
* log udf log in EventMessage for non_prod debug_info
* Remove enableAdtechCodeLogging flag value
* Remove Envoy Access Logging
* Route consented inference requests to a consented model store
* send chaff requests from SFE
* Service Mesh in AWS
* Support CPU isolation in the inference sidecar
* update code/cloud build to use tags
* Upgrade AWS Provider for Terraform from v3.xx to v4.xx
* Use gRPC for AWS Service Mesh Envoy HCs

### Bug Fixes

* [IsolateBuyerAndSellerCodeExecution] Add a new class for buyer's reporting code fetch and load
* [IsolateBuyerAndSellerCodeExecution] Add a new code wrapper with only scoreAd and reportResult
* [IsolateBuyerAndSellerCodeExecution] Add config flag to enable seller and buyer code isolation
* [IsolateBuyerAndSellerCodeExecution] Modify seller_udf_manager to fetch and load buyer udfs
* [IsolateBuyerAndSellerCodeExecution] Refactor the code fetch files.
* add check back in default grpc client
* Add DebugInfo pointer for debugging log into RomaRequestContext
* Add generation_id to chaff requests
* clean up log verbosity 3
* do not try to impersonate service accounts if TEST_MODE=true
* Eliminate Terraform Error Message about empty Authority Field
* Ensure instance id is set in logs on AWS when not using mesh.
* Execute Callback for empty HTTP request vector
* make num_chaff_requests not have a static lower bound
* scorecard.yaml version updates
* Upgrades google terraform plugin to 5.31.0 to fix crash

Bug: N/A
GitOrigin-RevId: faf77e5cbd6c2ae9f65761250ce95231c5f5ae08
Change-Id: I3e54553186f0ad82ffea0e43fa2ea3fbf22eb19f

diff --git a/production/packaging/aws/build_and_test b/production/packaging/aws/build_and_test
--- a/production/packaging/aws/build_and_test
+++ b/production/packaging/aws/build_and_test
@@ -36,8 +36,7 @@ function usage() {
 usage:
   $0 <options>
     --without-shared-cache       Containers will not mount ${HOME}/.cache/bazel
-    --server-image <image.tar>   Server docker image tarfile
-    --service-path               [REQUIRED] One of: auction_service, bidding_service, buyer_frontend_service, seller_frontend_service
+    --service                   [REQUIRED] At least one of: auction_service, bidding_service, buyer_frontend_service, seller_frontend_service. Use multiple times to specify more than one service.
     --with-ami                   AMI region in which to build and store AWS AMIs. Use multiple times to specify more than one region
     --aws-image-tag              Custom image tag for AMI image. Applied to AMI as tag value for key 'build_env'.
 
@@ -54,27 +53,21 @@ USAGE
 declare -a AMI_REGIONS
 declare BUILD_FLAVOR=prod
 declare AWS_IMAGE_TAG=""
+declare SERVICE_LIST=()
 
 while [[ $# -gt 0 ]]; do
   case "$1" in
-    --server-image)
-      SERVER_IMAGE="$2"
-      shift
-      shift
-      ;;
-    --service-path)
-      SERVICE="$2"
-      shift
-      shift
+    --service)
+      SERVICE_LIST+=("$2")
+      shift 2 || usage
       ;;
     --with-ami)
       AMI_REGIONS+=("$2")
-      shift
-      shift
+      shift 2 || usage
       ;;
     --aws-image-tag)
       AWS_IMAGE_TAG="$2"
-      shift 2
+      shift 2 || usage
       ;;
     --verbose)
       set -o xtrace
@@ -110,25 +103,36 @@ mkdir -p "${DIST}"/aws
 chmod 770 "${DIST}" "${DIST}"/aws
 
 printf "==== build AWS artifacts using build-amazonlinux2 =====\n"
-# build nitro enclave image, collect eif artifacts
-readonly IMAGE_URI=bazel/production/packaging/aws/${SERVICE}
-IMAGE_TAG=$(mktemp --dry-run temp-XXXXXX)
-readonly ENCLAVE_NAME=${SERVICE}
-builder::cbuild_al2 $"
-set -o errexit
-# extract server docker image into local docker client and retag it
-docker load -i ${SERVER_IMAGE}
-docker tag ${IMAGE_URI}:server_docker_image ${IMAGE_URI}:${IMAGE_TAG}
-nitro-cli build-enclave \
-  --docker-uri ${IMAGE_URI}:${IMAGE_TAG} \
-  --output-file /tmp/${ENCLAVE_NAME}.eif \
-  > /tmp/${ENCLAVE_NAME}_${BUILD_FLAVOR}.json
-if [[ $? -eq 0 ]]; then
-  mv /tmp/${ENCLAVE_NAME}.* dist/aws/
-  mv /tmp/${ENCLAVE_NAME}_${BUILD_FLAVOR}.* dist/aws/
-fi
-"
-docker image rm "${IMAGE_URI}:${IMAGE_TAG}"
+declare server_image=""
+declare image_uri=""
+declare image_tag=""
+for service in "${SERVICE_LIST[@]}"; do
+  server_image="dist/debian/${service}_image.tar"
+  if [[ ! -s ${WORKSPACE}/${server_image} ]]; then
+      printf "Error: docker image tar file not found: %s\n" "${server_image}" >&2
+      exit 1
+  fi
+
+  # build nitro enclave image, collect eif artifacts
+  image_uri="bazel/production/packaging/aws/${service}"
+  image_tag=$(mktemp --dry-run temp-XXXXXX)
+
+  builder::cbuild_al2 $"
+  set -o errexit
+  # extract server docker image into local docker client and retag it
+  docker load -i ${server_image}
+  docker tag ${image_uri}:server_docker_image ${image_uri}:${image_tag}
+  nitro-cli build-enclave \
+    --docker-uri ${image_uri}:${image_tag} \
+    --output-file /tmp/${service}.eif \
+    > /tmp/${service}_${BUILD_FLAVOR}.json
+  if [[ $? -eq 0 ]]; then
+    mv /tmp/${service}.* dist/aws/
+    mv /tmp/${service}_${BUILD_FLAVOR}.* dist/aws/
+  fi
+  "
+  docker image rm "${image_uri}:${image_tag}"
+done
 
 builder::cbuild_al2 $"
 trap _collect_logs EXIT
@@ -164,17 +168,21 @@ if [[ -n ${AMI_REGIONS[0]} ]]; then
   unzip -o -d "${DIST}"/aws "${DIST}"/aws/artifacts_proto.zip
   printf "==== build AWS AMI (using packer) =====\n"
   regions="$(arr_to_string_list AMI_REGIONS)"
-  build_version="$(git -C ${WORKSPACE} describe --tags --always || echo no-git-version)-${BUILD_FLAVOR}"
-  builder::cbuild_al2 "
+  build_version="$(git -C ${WORKSPACE} describe --tags --always || echo no-git-version)"
+  for service in "${SERVICE_LIST[@]}"; do
+    builder::cbuild_al2 "
 set -o errexit
 packer build \
   -var=regions='${regions}' \
-  -var=service=${SERVICE} \
+  -var=service=${service} \
   -var=git_commit=$(git rev-parse HEAD) \
+  -var=build_flavor=${BUILD_FLAVOR} \
   -var=build_version=${build_version} \
   -var=build_env=${AWS_IMAGE_TAG} \
   -var=distribution_dir=dist/aws \
   -var=workspace=/src/workspace \
   production/packaging/aws/common/ami/image.pkr.hcl
-"
+" &
+  done
+  wait
 fi
