Release 4.2.0 (2024-10-19)
### Features

* [BYOB] Add udf_execution metrics for generateBid
* add proto field to enable buyer debugging for eligible request
* adding aws inference dashboard
* Enable B&A experiments in GCP by splitting traffic
* enable buyer debugging for eligible request
* Implement Data Version Header for KV Server Clients
* Implement v2 bidding support - add branch selection
* Implement v2 bidding support - add kv_buyer_signals_adapter
* Implement v2 bidding support - update kv dependency
* output packer logs to stderr on AMI creation failure
* Pass data version to GenerateBidsRawRequest
* Support model deletion in model store
* Update Kv client to match the latest contract

### Bug Fixes

* Accumulate js_execution.errors_count metric
* Copy common signals instead of move in BuildProtectedAudienceBidRequest
* Fix changelog generation
* GCP demo terraform outputs url
* Prevent a potential read-after-delete bug in the inference benchmark
* start_bidding runs inference default js file
* typo in bidding_service_integration_test and buyer_code_wrapper

Bug: 374379327
GitOrigin-RevId: fe009c936554bbaa97d98a8823c1e9766de78b86
Change-Id: I5dc590ef23daa175d2edb5ac156916165871f963

diff --git a/production/packaging/aws/build_and_test b/production/packaging/aws/build_and_test
--- a/production/packaging/aws/build_and_test
+++ b/production/packaging/aws/build_and_test
@@ -102,7 +102,7 @@ DIST="${WORKSPACE}"/dist
 mkdir -p "${DIST}"/aws
 chmod 770 "${DIST}" "${DIST}"/aws
 
-printf "==== build AWS artifacts using build-amazonlinux2 =====\n"
+printf "==== build AWS artifacts using build-amazonlinux2023 =====\n"
 declare server_image=""
 declare image_uri=""
 declare image_tag=""
@@ -117,7 +117,7 @@ for service in "${SERVICE_LIST[@]}"; do
   image_uri="bazel/production/packaging/aws/${service}"
   image_tag=$(mktemp --dry-run temp-XXXXXX)
 
-  builder::cbuild_al2 $"
+  builder::cbuild_al2023 $"
   set -o errexit
   # extract server docker image into local docker client and retag it
   docker load -i ${server_image}
@@ -134,7 +134,7 @@ for service in "${SERVICE_LIST[@]}"; do
   docker image rm "${image_uri}:${image_tag}"
 done
 
-builder::cbuild_al2 $"
+builder::cbuild_al2023 $"
 trap _collect_logs EXIT
 function _collect_logs() {
   local -r -i STATUS=\$?
@@ -169,9 +169,12 @@ if [[ -n ${AMI_REGIONS[0]} ]]; then
   printf "==== build AWS AMI (using packer) =====\n"
   regions="$(arr_to_string_list AMI_REGIONS)"
   build_version="$(git -C ${WORKSPACE} describe --tags --always || echo no-git-version)"
+
+  packer_pids=()
+
   for service in "${SERVICE_LIST[@]}"; do
       log_file="${WORKSPACE}/dist/${service}_aws_build_log.txt"
-      (builder::cbuild_al2 "
+      (builder::cbuild_al2023 "
       set -o errexit
       packer build \
         -var=regions='${regions}' \
@@ -184,6 +187,24 @@ if [[ -n ${AMI_REGIONS[0]} ]]; then
         -var=workspace=/src/workspace \
         production/packaging/aws/common/ami/image.pkr.hcl
       " 2>&1 >> "$log_file") &
+      packer_pids+=($!)  # Store the packer build process ID
   done
-  wait
+
+  failed=0
+  i=0
+  for pid in "${packer_pids[@]}"; do
+    wait "${pid}" || {
+      built_service="${SERVICE_LIST[${i}]}"
+      service_build_logs="${WORKSPACE}/dist/${built_service}_aws_build_log.txt"
+      echo "----- Log output for $built_service -----" >&2
+      cat "${service_build_logs}" >&2
+      echo "Error: packer build failed for process ${pid} (service: ${built_service})." >&2
+      failed=1
+    }
+    i=$((i+1))
+  done
+
+  if [[ $failed -eq 1 ]]; then
+    exit 1
+  fi
 fi
