Release 0.8.0 (2023-07-12)
* add FetchUrls utility to MultiCurlHttpFetcher
* enable counter metrics with dp aggregation
* update multi-region.tf to use prod js urls and test mode true
* use //:non_prod_build to configure build

* Adjust all/small test configs
* Adjust sanitizer configs
* Correct example BFE hostname
* Correct license block
* Ensure --gcp-image flags are specified for gcp
* Ensure --instance flag is specified
* fix missing telemetry flag and readme
* Improve build_and_test_all_in_docker usage text

Bug: N/A
GitOrigin-RevId: 025fff9c627177c47f6afdece2c5b900ec81eccc
Change-Id: I2d941dde76790e539edb023cfbadba9ea1457583

diff --git a/production/packaging/build_and_test_all_in_docker b/production/packaging/build_and_test_all_in_docker
--- a/production/packaging/build_and_test_all_in_docker
+++ b/production/packaging/build_and_test_all_in_docker
@@ -1,20 +1,17 @@
 #!/bin/bash
+# Copyright 2023 Google LLC
 #
-# //  Copyright 2022 Google LLC
-# //
-# //  Licensed under the Apache License, Version 2.0 (the "License");
-# //  you may not use this file except in compliance with the License.
-# //  You may obtain a copy of the License at
-# //
-# //       http://www.apache.org/licenses/LICENSE-2.0
-# //
-# //  Unless required by applicable law or agreed to in writing, software
-# //  distributed under the License is distributed on an "AS IS" BASIS,
-# //  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# //  See the License for the specific language governing permissions and
-# //  limitations under the License.
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
 #
+#      http://www.apache.org/licenses/LICENSE-2.0
 #
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 
 set -o pipefail
 set -o errexit
@@ -32,7 +29,9 @@ function _print_runtime() {
     printf "build_and_test_in_docker completed successfully\n" &>/dev/stderr
   else
     printf "Error: build_and_test_in_docker completed with status code: %s\n" "${STATUS}" &>/dev/stderr
-    sleep 5s
+    if [[ -v KOKORO_ARTIFACTS_DIR ]]; then
+      sleep 5s
+    fi
   fi
   exit ${STATUS}
 }
@@ -51,15 +50,16 @@ declare GCP_IMAGE_TAG
 declare GCP_IMAGE_REPO
 
 function usage() {
-  local exitval=${1-1}
-  cat >&2 << USAGE
+  local -i -r exitval=${1-1}
+  cat >&2 <<USAGE
 usage:
   $0 <options>
-    --service-path               [REQUIRED] One of: auction_service, bidding_service, buyer_frontend_service, seller_frontend_service.
+    --service-path               [REQUIRED] Recognized values: auction_service, bidding_service, buyer_frontend_service, seller_frontend_service.
                                    Use multiple times to specify more than one service.
-    --instance                   [REQUIRED] Exactly one of: local, aws
-    --platform                   [REQUIRED] Exactly one of: gcp, aws
-    --build-flavor               [REQUIRED] Exactly one of: prod, non_prod; Turn on all vlog if set to: non_prod
+    --instance                   [REQUIRED] Recognized values: local, aws
+    --platform                   [REQUIRED] Recognized values: gcp, aws
+    --build-flavor               Recognized values: prod, non_prod. Default: prod
+                                   Use non_prod to enable verbose logging.
     --precommit-only             Run precommit then exit
     --no-precommit               Skip precommit checks
     --no-tests                   Skip tests
@@ -78,7 +78,6 @@ environment variables (all optional):
     BAZEL_EXTRA_ARGS             Additional command arguments to pass to bazel invocations
     EXTRA_DOCKER_RUN_ARGS        Additional arguments to pass to docker run invocations
 USAGE
-  # shellcheck disable=SC2086
   exit ${exitval}
 }
 
@@ -134,13 +133,26 @@ while [[ $# -gt 0 ]]; do
 done
 
 if [[ ${#SERVICES[@]} -eq 0 ]]; then
-  printf "A minimum of one --service-path must be specified\n" &>/dev/stderr
+  printf "Error: A minimum of one --service-path must be specified\n" &>/dev/stderr
   usage
 fi
-
 if [[ -z ${PLATFORM} ]]; then
-  printf "A platform must be specified\n" &>/dev/stderr
+  printf "Error: --platform must be specified\n" &>/dev/stderr
   usage
+fi
+if [[ -z ${INSTANCE} ]]; then
+  printf "Error: --instance must be specified\n" &>/dev/stderr
+  usage
+fi
+if [[ ${PLATFORM} = gcp ]]; then
+  if [[ -z ${GCP_IMAGE_TAG} ]]; then
+    printf "Error: --gcp-image-tag must be specified\n" &>/dev/stderr
+    usage
+  fi
+  if [[ -z ${GCP_IMAGE_REPO} ]]; then
+    printf "Error: --gcp-image-repo must be specified\n" &>/dev/stderr
+    usage
+  fi
 fi
 
 SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
